// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package io.joyrpc.example.service;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.joyrpc.example.service.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
