// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package io.joyrpc.example.service;

public final class HelloProto {
  private HelloProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_joyrpc_example_service_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_joyrpc_example_service_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_joyrpc_example_service_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_joyrpc_example_service_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ngrpc.proto\022\031io.joyrpc.example.service\"" +
      "\034\n\014HelloRequest\022\014\n\004name\030\001 \001(\t\" \n\rHelloRe" +
      "sponse\022\017\n\007message\030\001 \001(\t2n\n\013DemoService\022_" +
      "\n\010sayHello\022\'.io.joyrpc.example.service.H" +
      "elloRequest\032(.io.joyrpc.example.service." +
      "HelloResponse\"\000B\016B\nHelloProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_io_joyrpc_example_service_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_joyrpc_example_service_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_joyrpc_example_service_HelloRequest_descriptor,
        new String[] { "Name", });
    internal_static_io_joyrpc_example_service_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_joyrpc_example_service_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_joyrpc_example_service_HelloResponse_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
