// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package io.joyrpc.example.service;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.joyrpc.example.service.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>optional string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
